name: Axel Valdez
description: Designer based in Hermosillo, Mexico. Websites, Apps, logo, illustration, lettering, HTML and CSS.
author: Axel Valdez
category_dir: /blog/
url: http://axelvaldez.mx/
permalink: /blog/:year/:month/:title/
